# Generated by Django 5.0 on 2024-01-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('anons', models.CharField(max_length=250, verbose_name='Анонс')),
                ('text', models.TextField(verbose_name='Текст')),
                ('img', models.ImageField(upload_to='', verbose_name='Картинка')),
                ('date', models.DateField(verbose_name='Дата публикации')),
            ],
        ),
    ]
